### ISSUE TITLE
Spyder version & spyder-kernels versions

### ISSUE THREAD

**Issue by tyers** [spyder-ide/spyder-docs#307] opened 2022-02-09 15:54 UTC
As per https://github.com/spyder-ide/spyder/issues/17257 opening this ticket against the docs.

The information in the [troubleshooting pages](https://docs.spyder-ide.org/current/troubleshooting/common-illnesses.html#spyder-kernels-not-installed-incompatible) relating to the versions of spyder-kernels is out of date and does not include spyder releases > 5.1.5.

It would also be helpful to include the compatible spyder-kernel versions in the release notes of a given spyder release.

**Comment by CAM-Gerlach** [comment] 2022-02-16 02:02
Thanks! Sorry for the delay; was on a trip. It looks like this is a duplicate of #308 , which contains more detail, so I'll merge this with that one. I'll take care of it as soon as I can confirm which versions we should add. Thanks again!

**Comment by CAM-Gerlach** [comment] 2022-02-16 02:10
Actually, this refers to the troubleshooting guide, while the other issue talks about the FAQ, so I'll keep them both open and close them both in the same PR.

**Comment by CAM-Gerlach** [comment] 2022-02-16 02:25
As a quick update, I opened #309 to resolve this (and #308)

**Closed** 2022-02-17 18:42 UTC
Labels: type:Spyder Change
