### ISSUE TITLE
Can't figure out difference between Spyder.dmg and Spyder-Lite.dmg

### ISSUE THREAD

**Issue by nbelakovski** [spyder-ide/spyder-docs#215] opened 2020-12-26 08:13 UTC
I'm ignoring the normal template since this is a documentation issue.

I see a Spyder-Lite.dmg in the assets on the releases page. I'm guess it's a version of Spyder without numpy, etc., but I can't find anything in any docs to confirm or deny this. I'm happy to make a PR to add to the docs, but of course I can't do that if I don't know what it is

**Comment by CAM-Gerlach** [comment] 2020-12-27 00:57
Sorry for the confusion, @nbelakovski , and thanks for letting us know. We actually already have an issue in progress, #201 , to document this (and several other key points with the new installers); its next in line after we finish PR #213 and porting the deployment of the docs over to Github actions, so it should be addressed in the next couple weeks.

To actually answer your question, the difference between the "full" and "lite" installers for Windows and Mac (highly inconsistent naming aside), is that the "full" version includes Spyder's optional dependencies (Numpy, SciPy, Pandas, Matplotlib, Cython and Sympy), which enable interactive plotting in the Plots pane, browsing and editing arrays and DataFrames in the Variable Explorer, additional data import formats, and specialized Cython and SymPy consoles.

Closed as duplicate of #201 ; feel free to continue the discussion there, thanks.

**Closed by CAM-Gerlach** 2020-12-27 00:57 UTC

**Comment by nbelakovski** [comment] 2020-12-27 04:23
Thanks @CAM-Gerlach !
