### ISSUE TITLE
Mention how to run cells

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder-docs#97] opened 2019-05-11 22:05 UTC
I couldn't find a mention about how to run cells in our docs, even though we mention how to create them. This is a serious issue we should solve as soon as possible.

**Comment by CAM-Gerlach** [comment] 2019-05-11 22:26
Well, to be fair we don't say how to run files or lines either, which are even more basic constructs and located in the same place as running code cells, so we have our work cut out for us here...

**Comment by ccordoba12** [comment] 2019-05-11 23:24
Yeah, but this prevents to quote our docs to answer questions like this:

https://stackoverflow.com/questions/56086764/section-divider-in-spyder

**Comment by CAM-Gerlach** [comment] 2019-05-11 23:26
Yeah, this absolutely does need to be in there. My only point is that we are missing a lot in our docs (no thanks to me), and there's so much I need to do, which discourages me sometimes. But hey, its a [starfish](https://www.cityyear.org/about-us/culture-values/founding-stories/starfish-story)

**Comment by CAM-Gerlach** [comment] 2020-06-28 05:00
Hey @juanis2112 could you the reason this was closed?

**Comment by juanis2112** [comment] 2020-06-28 06:16
There is another open issue about it @CAM-Gerlach

**Comment by CAM-Gerlach** [comment] 2020-06-28 17:27
I see. In that case, a comment should be left along the lines of `Closed as a duplicate of #XXXX` so its clear why it was closed, and links to the canonical issue so that those finding this one know where to go to track it further. As it stands, I'm not sure what issue that is, even after looking through all of them. Thanks!

**Comment by juanis2112** [comment] 2020-06-28 18:28
duplicate of #40

**Comment by CAM-Gerlach** [comment] 2020-06-28 18:59
They do seem similar at first glance, but actually, #40 is about documenting how cell names now appear in the Outline pane, while this one is about how to run cells in the Editor. So, it seems this should be re-opened.

**Comment by ccordoba12** [comment] 2020-06-29 01:28
I agree with @CAM-Gerlach. #40 and this one are different, so let's reopen it.

**Comment by hyounes4560** [comment] 2022-07-28 01:29
@ccordoba12 @steff456 should we consider adding this to the Editor docs?

**Comment by steff456** [comment] 2022-07-28 02:27
Yes! In the outline I already left a short overview for this section just to complement the current editor docs. Just let me know if you need any extra information about code cells 😉

**Comment by hyounes4560** [comment] 2022-07-28 02:33
> Yes! In the outline I already left a short overview for this section just to complement the current editor docs. Just let me know if you need any extra information about code cells 😉

Sure will do.

**Comment by CAM-Gerlach** [comment] 2022-07-28 02:33
Yes, this would be extremely helpful, thanks :+1:

**Closed** 2022-11-15 07:09 UTC
Labels: type:Enhancement
